version: "3.7"
services:

#  redis:
#    build: ./redis
#    restart: always
#    ports:
#      - "6379:6379"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:8080"

  epd-be:
    build: ./nodejs
    restart: always
    ports:
      - "7676:7676"
